name = "q1cc-simple-modpack"
author = "xicesky"
version = "0.1.1-1.20.1"
description = "A multiplayer \"factory building\" experience focused on Create"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dfccbcdaa06303532ec5774feebbe6daf1af4d1e8a27fffbbcac36c19818efb"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
